# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'validui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1307, 942)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.label_title = QtGui.QLabel(self.centralWidget)
        self.label_title.setGeometry(QtCore.QRect(520, 20, 251, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(570, 80, 151, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_image = QtGui.QLabel(self.centralWidget)
        self.label_image.setGeometry(QtCore.QRect(160, 120, 981, 120))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setObjectName(_fromUtf8("label_image"))
        self.btn_auto_test = QtGui.QPushButton(self.centralWidget)
        self.btn_auto_test.setGeometry(QtCore.QRect(740, 740, 301, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_auto_test.sizePolicy().hasHeightForWidth())
        self.btn_auto_test.setSizePolicy(sizePolicy)
        self.btn_auto_test.setObjectName(_fromUtf8("btn_auto_test"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(166, 666, 48, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.edit_big_height = QtGui.QLineEdit(self.centralWidget)
        self.edit_big_height.setEnabled(False)
        self.edit_big_height.setGeometry(QtCore.QRect(220, 666, 341, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_big_height.sizePolicy().hasHeightForWidth())
        self.edit_big_height.setSizePolicy(sizePolicy)
        self.edit_big_height.setObjectName(_fromUtf8("edit_big_height"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(166, 704, 48, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.edit_big_length = QtGui.QLineEdit(self.centralWidget)
        self.edit_big_length.setEnabled(False)
        self.edit_big_length.setGeometry(QtCore.QRect(220, 704, 341, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_big_length.sizePolicy().hasHeightForWidth())
        self.edit_big_length.setSizePolicy(sizePolicy)
        self.edit_big_length.setObjectName(_fromUtf8("edit_big_length"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(166, 742, 48, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.edit_small_height = QtGui.QLineEdit(self.centralWidget)
        self.edit_small_height.setEnabled(False)
        self.edit_small_height.setGeometry(QtCore.QRect(220, 742, 341, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_small_height.sizePolicy().hasHeightForWidth())
        self.edit_small_height.setSizePolicy(sizePolicy)
        self.edit_small_height.setObjectName(_fromUtf8("edit_small_height"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(166, 780, 48, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.edit_small_length = QtGui.QLineEdit(self.centralWidget)
        self.edit_small_length.setEnabled(False)
        self.edit_small_length.setGeometry(QtCore.QRect(220, 780, 341, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_small_length.sizePolicy().hasHeightForWidth())
        self.edit_small_length.setSizePolicy(sizePolicy)
        self.edit_small_length.setObjectName(_fromUtf8("edit_small_length"))
        self.lineEdit_5 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(220, 820, 241, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.btn_start_system = QtGui.QPushButton(self.centralWidget)
        self.btn_start_system.setGeometry(QtCore.QRect(740, 660, 151, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start_system.sizePolicy().hasHeightForWidth())
        self.btn_start_system.setSizePolicy(sizePolicy)
        self.btn_start_system.setObjectName(_fromUtf8("btn_start_system"))
        self.btn_close_system = QtGui.QPushButton(self.centralWidget)
        self.btn_close_system.setGeometry(QtCore.QRect(900, 660, 141, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_system.sizePolicy().hasHeightForWidth())
        self.btn_close_system.setSizePolicy(sizePolicy)
        self.btn_close_system.setObjectName(_fromUtf8("btn_close_system"))
        self.label_canny = QtGui.QLabel(self.centralWidget)
        self.label_canny.setGeometry(QtCore.QRect(160, 250, 981, 150))
        self.label_canny.setObjectName(_fromUtf8("label_canny"))
        self.btn_savefile = QtGui.QPushButton(self.centralWidget)
        self.btn_savefile.setGeometry(QtCore.QRect(480, 820, 75, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_savefile.sizePolicy().hasHeightForWidth())
        self.btn_savefile.setSizePolicy(sizePolicy)
        self.btn_savefile.setObjectName(_fromUtf8("btn_savefile"))
        self.progressBar = QtGui.QProgressBar(self.centralWidget)
        self.progressBar.setGeometry(QtCore.QRect(750, 830, 301, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.table = QtGui.QTableView(self.centralWidget)
        self.table.setGeometry(QtCore.QRect(120, 420, 1081, 192))
        self.table.setObjectName(_fromUtf8("table"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_title.setText(_translate("MainWindow", "宝钢自动钢丝测量仪", None))
        self.label_2.setText(_translate("MainWindow", "开发单位：上海交通大学", None))
        self.label_image.setText(_translate("MainWindow", "图像981*80,从2452*200变换得来。显示区域稍微大一些", None))
        self.btn_auto_test.setText(_translate("MainWindow", "自动测量", None))
        self.label_4.setText(_translate("MainWindow", "大波波高", None))
        self.label_5.setText(_translate("MainWindow", "大波波长", None))
        self.label_6.setText(_translate("MainWindow", "小波波高", None))
        self.label_7.setText(_translate("MainWindow", "小波波长", None))
        self.btn_start_system.setText(_translate("MainWindow", "打开系统", None))
        self.btn_close_system.setText(_translate("MainWindow", "关闭系统", None))
        self.label_canny.setText(_translate("MainWindow", "图像981*80,从2452*200变换得来。显示提取后的边缘，要更大的显示区域", None))
        self.btn_savefile.setText(_translate("MainWindow", "保存", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

